sudo: false
language: node_js
node_js:
  - "stable"
  - "6"
  - "4"
before_install:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
install_script:
  - npm i
script:
  - node_modules/.bin/mocha --reporter spec --timeout 6000 test/main.js
  - gulp lint_diff
